# Generated by Django 4.1.6 on 2023-03-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_products_date_alter_products_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
